version: '2'

services:
    zookeeper:
        image: 'confluentinc/cp-zookeeper:latest'
        hostname: zookeeper
        container_name: kafka-test-zookeeper
        ports:
            - '2181:2181'
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    broker:
        image: 'confluentinc/cp-server:latest'
        hostname: broker
        container_name: kafka-test-broker
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
            - '9093:9093'
            - '9094:9094'
            - '9095:9095'
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092, SSL://localhost:9093
            KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker.keystore.jks
            KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_keystore_creds
            KAFKA_SSL_KEY_CREDENTIALS: broker_sslkey_creds
            KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker.truststore.jks
            KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker_truststore_creds
        volumes:
            - ./_resources/trustoresandkeystores/broker_keystore_creds:/etc/kafka/secrets/broker_keystore_creds
            - ./_resources/trustoresandkeystores/broker_sslkey_creds:/etc/kafka/secrets/broker_sslkey_creds
            - ./_resources/trustoresandkeystores/broker_truststore_creds:/etc/kafka/secrets/broker_truststore_creds
            - ./_resources/trustoresandkeystores/kafka.broker.keystore.jks:/etc/kafka/secrets/kafka.broker.keystore.jks
            - ./_resources/trustoresandkeystores/kafka.broker.truststore.jks:/etc/kafka/secrets/kafka.broker.truststore.jks
