[package]
org = "ballerina"
name = "websubhub"
version = "@toml.version@"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/websubhub-native-@project.version@.jar"
