[consolidatorService.config]
# IP and Port of the Kafka bootstrap node
KAFKA_BOOTSTRAP_NODE = "localhost:9092"

# Kafka topic which will get notified for websub subscription/unsubscription
# All the hubs must be pointed to the same Kafka topic to notify websub subscription/unsubscription
SUBSCRIBERS_TOPIC = "registered-subscribers"

# Kafka topic which is stores consolidated websub subscribers for this server
CONSOLIDATED_SUBSCRIBERS_TOPIC = "consolidated-subscribers";

# The interval in which Kafka consumers wait for new messages
POLLING_INTERVAL = 10.0

# The period in which Kafka close method waits to complete
GRACEFUL_CLOSE_PERIOD = 5.0
