resources:
  - in_memory_hub.yaml
  - service.yaml

patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: in-memory-hub-deployment
